background_opacity	0.75
#font_family             Symbols Nerd Font
#font_family             ProggyClean Nerd Font
#font_family             Departureono Nerd Font
#font_family             DaddyTimeMono Nerd Font
#font_family             ShureTechMono Nerd Font
#font_family             ttf-bigblueterminal-nerd
#font_family             GreyQo-Regular
font_family             3270 Nerd Font
