preload = /home/michael/Pictures/CodeWall/image1.png
preload = /home/michael/Pictures/CodeWall/image2.png
preload = /home/michael/Pictures/CodeWall/image3.png
preload = /home/michael/Pictures/CodeWall/image4.png
preload = /home/michael/Pictures/CodeWall/image5.png
preload = /home/michael/Pictures/CodeWall/image6.png
preload = /home/michael/Pictures/CodeWall/image7.png
preload = /home/michael/Pictures/CodeWall/image8.png
preload = /home/michael/Pictures/CodeWall/image9.png
preload = /home/michael/Pictures/CodeWall/image10.png
wallpaper = ,/home/michael/Pictures/CodeWall/image1.png
#preload = /home/michael/Pictures/FirePenguin.jpg
#wallpaper = ,/home/michael/Pictures/FirePenguin.jpg
