format = """$os[◣](fg:col6 bg:col5)\
$hostname[◣](fg:col5 bg:col4)\
$username[◣](fg:col4 bg:col3)\
$directory[◣](fg:col3 bg:col2)\
[ 󰊢 ](fg:text2 bg:col2)$git_branch$git_status[◣](fg:col2 bg:col1)\
$shell[◣](fg:col1)\
$sudo\
$fill\
$cmd_duration\
$line_break\
$character\
"""

# $conda[◣](fg:green bg:blue)\
# $nix_shell[◣](fg:blue bg:violet)\
palette = "pale"
[palettes.monokai]
dim_gray = "#363636"
darkred = "#660000"
red = "#fd6883"
orange = "#f38d70"
yellow = "#f9cc6c"
green = "#adda78"
blue = "#6ab0f3"
violet = "#c397d8"


[palettes.pale]
dim_gray = "#363636"
darkred = "#660000"
red = "#dd5f6a"
orange = "#ff9070"
yellow = "#f9cc9c"
green = "#adda90"
blue = "#7aa2f3"
violet = "#b397d8"
col1 = "#fdd663"
col2 = "#f29b14"
col3 = "#d26e0a"
col4 = "#b64701"
col5 = "#8c3600"
col6 = "#632600"
text1 = "#222222"
text2 = "#222222"
text3 = "#222222"
text4 = "#cccccc"
text5 = "#cccccc"
text6 = "#cccccc"

[character]
disabled = false
success_symbol = "[❯](col1)"

[os]
disabled = false
format = "[ $symbol ]($style)"
style = "bg:col6 fg:text6"

[shell]
disabled = false
format = "[ $indicator ]($style)"
style = "fg:text1 bg:col1"
fish_indicator = "󰈺"
zsh_indicator = "󰰶"
bash_indicator = ""
xonsh_indicator = "󰌠"
nu_indicator = "[nu](italic $style)"
unknown_indicator = ""

[os.symbols]
Arch = "󰣇"
Debian = ""
Fedora = ""
Linux = ""
Macos = ""
NixOS = ""
Ubuntu = "󰕈"
# Vanilla = ""
# Windows = "" HAHAHA AS IF

[username]
format = "[ $user ]($style)"
show_always = true
style_user = "bg:col4 fg:text4"
style_root = "bg:col4 fg:text4"

[directory]
format = "[ $path ]($style)"
style = "bg:col3 fg:text3"
fish_style_pwd_dir_length = 1

[git_branch]
format = "[ $branch ]($style)"
symbol = ""
style = "bg:col2 fg:text2"

[git_status]
format = '[\[$all_status$ahead_behind\] ]($style)'
style = "bg:col2 fg:text2"
ignore_submodules = true

[nix_shell]
disabled = false
format = "$state"
pure_msg = "[  ](bg:blue fg:green)"
impure_msg = "[  ](bg:blue fg:red)"
unknown_msg = "[  ](bg:blue fg:yellow)"

[conda]
disabled = false
format = "[ $environment ]($style)"
style = "bg:green fg:dim_gray"

[status]
disabled = false

[sudo]
disabled = false
format = "[...](fg:bold black)[◥](fg:red)[ SUDO ](fg:text1 bg:red bold)[◣](fg:red)"

[hostname]
disabled = false
ssh_only = false
format = "[ $hostname ](fg:text5 bg:col5)"


[fill]
symbol = '.'
